cam_dev=/dev/video0
capture_width=800
capture_height=600
rknn_model_path=matmul_corr.rknn
quality_mode=enabled
quality_lost_threshold=0.40
quality_display_threshold=0.20
min_crop=512.0
max_crop=512.0
decode_argmax_only=1
iterations_num=3
