cam_dev=/dev/video0
capture_width=640
capture_height=480
rknn_model_path=matmul_corr.rknn
quality_mode=enabled
quality_lost_threshold=0.10
quality_display_threshold=0.10
min_crop=400.0
max_crop=400.0
decode_argmax_only=1
iterations_num=2
