cam_dev=/dev/video0
capture_width=640
capture_height=480
rknn_template_model_path=tracker_template.rknn
rknn_search_backbone_model_path=tracker_search_backbone.rknn
rknn_decoder_model_path=tracker_decoder.rknn
quality_mode=disabled
min_crop=64.0
max_crop=256.0
